/* Automatically generated by wasm2c */
#ifndef WASM_H_GENERATED_
#define WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;

typedef struct w2c_add {
  struct w2c_env* w2c_env_instance;
} w2c_add;

void wasm2c_add_instantiate(w2c_add*, struct w2c_env*);
void wasm2c_add_free(w2c_add*);
wasm_rt_func_type_t wasm2c_add_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'log' */
void w2c_env_log(struct w2c_env*, u32);

/* export: 'run' */
void w2c_add_run(w2c_add*);

#ifdef __cplusplus
}
#endif

#endif  /* WASM_H_GENERATED_ */
